name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > github_key.pem
          chmod 600 github_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i github_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update -y

            # Install Docker if not installed
            if ! command -v docker &> /dev/null
            then
                echo "Installing Docker..."
                sudo apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
                sudo usermod -aG docker $USER
            fi

            # Install Docker Compose if not installed
            if ! docker compose version &> /dev/null
            then
                echo "Installing Docker Compose..."
                sudo apt install -y docker-compose-plugin
            fi

            # Set permissions for Docker
            sudo chmod 666 /var/run/docker.sock

            # Navigate to the app directory or clone if missing
            cd /home/${{ secrets.EC2_USERNAME }}
            if [ ! -d "flask-app" ]; then
                git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO.git flask-app
            fi
            cd flask-app
            git pull origin main

            # Stop and remove existing containers
            docker compose down || docker-compose down

            # Build and start new containers
            docker compose up --build -d || docker-compose up --build -d

            # Remove unused Docker images
            docker image prune -f
          EOF
